## Multiple Linear Regression

#### <b>Problem Statement</b> is to create a model to predict the attrition rate of an employee.

I am going to use MLR after converting the feature varibles I think are important into categorical variable that can take only 2 values,1 and 0.

### 1. Importing Data and Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import copy
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor 
from sklearn import linear_model

In [2]:
file = pd.read_csv('Train.csv')
file.dropna(inplace=True)
file

Employee_ID Gender   Age  Education_Level Relationship_Status  \
0      EID_23371      F  42.0                4             Married   
1      EID_18000      M  24.0                3              Single   
2       EID_3891      F  58.0                3             Married   
4      EID_22534      F  31.0                1             Married   
5       EID_2278      M  54.0                3             Married   
...          ...    ...   ...              ...                 ...   
6995   EID_16328      F  23.0                5             Married   
6996    EID_8387      F  44.0                1             Married   
6997    EID_8077      F  49.0                3              Single   
6998   EID_19597      F  47.0                3             Married   
6999    EID_1640      F  58.0                3             Married   

         Hometown        Unit Decision_skill_possess  Time_of_service  \
0        Franklin          IT             Conceptual              4.0   
1     Springfield   Logistics             Analytical              5.0   
2         Clinton     Quality             Conceptual             27.0   
4     Springfield   Logistics             Conceptual              5.0   
5         Lebanon  Purchasing             Conceptual             19.0   
...           ...         ...                    ...              ...   
6995     Franklin  Operarions             Behavioral              4.0   
6996      Lebanon         R&D             Analytical             16.0   
6997  Springfield          IT              Directive             10.0   
6998   Washington       Sales             Behavioral             24.0   
6999     Franklin          IT              Directive             22.0   

      Time_since_promotion  ...  Compensation_and_Benefits  Work_Life_balance  \
0                        4  ...                      type2                3.0   
1                        4  ...                      type2                4.0   
2                        3  ...                      type2                1.0   
4                        4  ...                      type3                3.0   
5                        1  ...                      type2                1.0   
...                    ...  ...                        ...                ...   
6995                     1  ...                      type3                3.0   
6996                     2  ...                      type3                3.0   
6997                     1  ...                      type2                4.0   
6998                     1  ...                      type0                2.0   
6999                     2  ...                      type2                3.0   

      VAR1    VAR2    VAR3  VAR4  VAR5  VAR6  VAR7  Attrition_rate  
0        4  0.7516  1.8688   2.0     4     5     3          0.1841  
1        3 -0.9612 -0.4537   2.0     3     5     3          0.0670  
2        4 -0.9612 -0.4537   3.0     3     8     3          0.0851  
4        1  0.7516 -0.4537   2.0     2     8     2          0.1827  
5        3 -1.8176  1.8688   2.0     2     8     3          0.7613  
...    ...     ...     ...   ...   ...   ...   ...             ...  
6995     1  0.7516 -0.4537   2.0     3     7     3          0.7839  
6996     2 -0.1048 -2.7762   2.0     4     8     4          0.1055  
6997     2 -0.1048 -0.4537   2.0     4     8     3          0.7847  
6998     4  0.7516  1.8688   2.0     3     6     3          0.4162  
6999     3 -0.1048 -1.6150   3.0     4     5     3          0.0910  

[5353 rows x 24 columns]

### 2. EDA and Feature Variables

#### A. Decision Skill Process

I feel Analytical people are more likely to leave a company because they might not be emotionally attached with the company. I tested it but it was wrong and hence I dropped it.

In [3]:
column_values = file[["Decision_skill_possess"]].values
unique_values = np.unique(column_values)
unique_values

array(['Analytical', 'Behavioral', 'Conceptual', 'Directive'],
      dtype=object)

#### B. Compensation_and_Benefits

This varible might have some importance but I am not able to understand the which type has more importance

In [4]:
column_values = file[["Compensation_and_Benefits"]].values
unique_values = np. unique(column_values)
unique_values

array(['type0', 'type1', 'type2', 'type3', 'type4'], dtype=object)

#### C. Unit

Every department has different attrition rate and hence we should run different models for each Unit.

In [5]:
column_values = file[["Unit"]].values
unique_values = np. unique(column_values)
unique_values

array(['Accounting and Finance', 'Human Resource Management', 'IT',
       'Logistics', 'Marketing', 'Operarions', 'Production', 'Purchasing',
       'Quality', 'R&D', 'Sales', 'Security'], dtype=object)

#### D. Growth Rate

This will have importance on attrition rate, we have to decide what would be the cutoff value for the person to leave the company.

In [6]:
file[["growth_rate"]].describe()

growth_rate
count  5353.000000
mean     47.035494
std      15.750384
min      20.000000
25%      33.000000
50%      47.000000
75%      61.000000
max      74.000000

In [7]:
file[["VAR1"]].describe()

VAR1
count  5353.000000
mean      3.095647
std       0.844288
min       1.000000
25%       3.000000
50%       3.000000
75%       4.000000
max       5.000000

In [8]:
column_values = file[["VAR1"]].values
unique_values = np. unique(column_values)
unique_values

array([1, 2, 3, 4, 5], dtype=int64)

In [9]:
column_values = file[["VAR4"]].values
unique_values = np. unique(column_values)
unique_values

array([1., 2., 3.])

In [10]:
file[["VAR4"]].describe()

VAR4
count  5353.000000
mean      1.893518
std       0.527514
min       1.000000
25%       2.000000
50%       2.000000
75%       2.000000
max       3.000000

In [11]:
column_values = file[["VAR5"]].values
unique_values = np. unique(column_values)
unique_values

array([1, 2, 3, 4, 5], dtype=int64)

In [12]:
file[["VAR5"]].describe()

VAR5
count  5353.000000
mean      2.839156
std       0.939750
min       1.000000
25%       2.000000
50%       3.000000
75%       3.000000
max       5.000000

In [13]:
column_values = file[["VAR6"]].values
unique_values = np. unique(column_values)
unique_values

array([5, 6, 7, 8, 9], dtype=int64)

In [14]:
file[["VAR6"]].describe()

VAR6
count  5353.000000
mean      7.105548
std       1.160621
min       5.000000
25%       6.000000
50%       7.000000
75%       8.000000
max       9.000000

In [15]:
column_values = file[["VAR7"]].values
unique_values = np. unique(column_values)
unique_values

array([1, 2, 3, 4, 5], dtype=int64)

In [16]:
file[["VAR7"]].describe()

VAR7
count  5353.000000
mean      3.248459
std       0.919758
min       1.000000
25%       3.000000
50%       3.000000
75%       4.000000
max       5.000000

#### E. Pay Scale

People with lower pay scale tend to leave the company.

In [17]:
column_values = file[["Pay_Scale"]].values
unique_values = np. unique(column_values)
unique_values

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### F. Post Level

People with higher post are less likely to leave the company.

In [18]:
column_values = file[["Post_Level"]].values
unique_values = np. unique(column_values)
unique_values

array([1, 2, 3, 4, 5], dtype=int64)

#### G. Work LIfe Balance

People who think they have good work life balance don't leave the company

In [19]:
column_values = file[["Work_Life_balance"]].values
unique_values = np. unique(column_values)
unique_values

array([1., 2., 3., 4., 5.])

#### H. Age

Older people are less likely to leave to company.

#### H. Education

Educated people are more likely leave the company.

In [20]:
df = pd.DataFrame(index=file.index).fillna(0.0)

In [21]:
df['Employee_ID']=file['Employee_ID']
df['VAR3']=file['VAR3']
df['VAR2']=file['VAR2']


# df['VAR6']=file['VAR6']
# df['VAR5']=file['VAR5']
# df['VAR4']=file['VAR4']
# df['VAR1']=file['VAR1']

df['Attrition_rate']=file['Attrition_rate']


        
df['Unit1']=np.where(file['Unit']=='Accounting and Finance',1,0)
df['Unit2']=np.where(file['Unit']=='Human Resource Management',1,0)    
df['Unit3']=np.where(file['Unit']=='IT',1,0)    
df['Unit4']=np.where(file['Unit']=='Logistics',1,0)    
df['Unit5']=np.where(file['Unit']=='Marketing',1,0)    
df['Unit6']=np.where(file['Unit']=='Operarions',1,0)    
df['Unit7']=np.where(file['Unit']=='Production',1,0)    
df['Unit8']=np.where(file['Unit']=='Purchasing',1,0)    
df['Unit9']=np.where(file['Unit']=='Quality',1,0)    
df['Unit10']=np.where(file['Unit']=='R&D',1,0)    
df['Unit11']=np.where(file['Unit']=='Sales',1,0)    
df['Unit12']=np.where(file['Unit']=='Security',1,0)  


df['Time_of_service']=file['Time_of_service']
df['Age']=file['Age']
df['Education']=file['Education_Level']
df['Relationship_Status']=np.where(file['Relationship_Status']=='Single',1,0)
df['Time_since_promotion']=file['Time_since_promotion']
df['growth_rate']=file['growth_rate']
df['Pay_Scale']=file['Pay_Scale']
df['Post_Level']=file['Post_Level']
df['Work_Life_balance']=file['Work_Life_balance']

In [22]:
df

Employee_ID    VAR3    VAR2  Attrition_rate  Unit1  Unit2  Unit3  Unit4  \
0      EID_23371  1.8688  0.7516          0.1841      0      0      1      0   
1      EID_18000 -0.4537 -0.9612          0.0670      0      0      0      1   
2       EID_3891 -0.4537 -0.9612          0.0851      0      0      0      0   
4      EID_22534 -0.4537  0.7516          0.1827      0      0      0      1   
5       EID_2278  1.8688 -1.8176          0.7613      0      0      0      0   
...          ...     ...     ...             ...    ...    ...    ...    ...   
6995   EID_16328 -0.4537  0.7516          0.7839      0      0      0      0   
6996    EID_8387 -2.7762 -0.1048          0.1055      0      0      0      0   
6997    EID_8077 -0.4537 -0.1048          0.7847      0      0      1      0   
6998   EID_19597  1.8688  0.7516          0.4162      0      0      0      0   
6999    EID_1640 -1.6150 -0.1048          0.0910      0      0      1      0   

      Unit5  Unit6  ...  Unit12  Time_of_service   Age  Education  \
0         0      0  ...       0              4.0  42.0          4   
1         0      0  ...       0              5.0  24.0          3   
2         0      0  ...       0             27.0  58.0          3   
4         0      0  ...       0              5.0  31.0          1   
5         0      0  ...       0             19.0  54.0          3   
...     ...    ...  ...     ...              ...   ...        ...   
6995      0      1  ...       0              4.0  23.0          5   
6996      0      0  ...       0             16.0  44.0          1   
6997      0      0  ...       0             10.0  49.0          3   
6998      0      0  ...       0             24.0  47.0          3   
6999      0      0  ...       0             22.0  58.0          3   

      Relationship_Status  Time_since_promotion  growth_rate  Pay_Scale  \
0                       0                     4           33        7.0   
1                       1                     4           36        6.0   
2                       0                     3           51        8.0   
4                       0                     4           62        2.0   
5                       0                     1           21        9.0   
...                   ...                   ...          ...        ...   
6995                    0                     1           20        6.0   
6996                    0                     2           59        4.0   
6997                    1                     1           59        3.0   
6998                    0                     1           21        8.0   
6999                    0                     2           74        5.0   

      Post_Level  Work_Life_balance  
0              1                3.0  
1              3                4.0  
2              2                1.0  
4              3                3.0  
5              5                1.0  
...          ...                ...  
6995           2                3.0  
6996           2                3.0  
6997           2                4.0  
6998           5                2.0  
6999           4                3.0  

[5353 rows x 25 columns]

### 3. Regression Modelling

In [23]:
X = df[['VAR3','VAR2','Unit1','Unit2','Unit3','Unit4','Unit5','Unit6','Unit7','Unit8','Unit9','Unit10','Unit11','Unit12','Time_of_service','Age', 'Education', 'Relationship_Status', 'Time_since_promotion', 'growth_rate', 'Pay_Scale', 'Post_Level','Work_Life_balance']].values
Y = df['Attrition_rate'].values

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [25]:
# from sklearn.ensemble import RandomForestRegressor
# reg = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# reg.fit(X_train, y_train);
reg = linear_model.Lasso()
# reg = LinearRegression()  
# reg=linear_model.Ridge(alpha=.4)
reg.fit(X_train, y_train)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [26]:
# reg.coef_

In [27]:
coef = pd.DataFrame()
coef['Coefficient']=reg.coef_
a=['VAR3','VAR2','Unit1','Unit2','Unit3','Unit4','Unit5','Unit6','Unit7','Unit8','Unit9','Unit10','Unit11','Unit12','Time_of_service','Age', 'Education', 'Relationship_Status', 'Time_since_promotion', 'growth_rate',  'Pay_Scale','Post_Level', 'Work_Life_balance']
coef['Variable']=np.array(a)
coef

Coefficient              Variable
0          -0.0                  VAR3
1          -0.0                  VAR2
2           0.0                 Unit1
3          -0.0                 Unit2
4          -0.0                 Unit3
5          -0.0                 Unit4
6          -0.0                 Unit5
7           0.0                 Unit6
8           0.0                 Unit7
9           0.0                 Unit8
10          0.0                 Unit9
11         -0.0                Unit10
12         -0.0                Unit11
13          0.0                Unit12
14         -0.0       Time_of_service
15         -0.0                   Age
16         -0.0             Education
17          0.0   Relationship_Status
18          0.0  Time_since_promotion
19         -0.0           growth_rate
20         -0.0             Pay_Scale
21          0.0            Post_Level
22          0.0     Work_Life_balance

In [28]:
y_pred = reg.predict(X_test)
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df2 = df1.head(25)
df2

Actual  Predicted
0   0.0544   0.187566
1   0.1683   0.187566
2   0.0366   0.187566
3   0.1779   0.187566
4   0.0451   0.187566
5   0.1970   0.187566
6   0.0134   0.187566
7   0.2376   0.187566
8   0.0781   0.187566
9   0.0904   0.187566
10  0.0637   0.187566
11  0.3726   0.187566
12  0.1789   0.187566
13  0.2737   0.187566
14  0.0071   0.187566
15  0.1914   0.187566
16  0.2863   0.187566
17  0.0686   0.187566
18  0.3245   0.187566
19  0.2612   0.187566
20  0.2326   0.187566
21  0.0313   0.187566
22  0.2740   0.187566
23  0.2464   0.187566
24  0.1525   0.187566

In [29]:
test = pd.read_csv("Test.csv")
test.fillna(test.mean(), inplace=True)
df_test = pd.DataFrame()

In [30]:
df_test['VAR3']=test['VAR3']
df_test['VAR2']=test['VAR2']

df_test['Unit1']=np.where(test['Unit']=='Accounting and Finance',1,0)
df_test['Unit2']=np.where(test['Unit']=='Human Resource Management',1,0)    
df_test['Unit3']=np.where(test['Unit']=='IT',1,0)    
df_test['Unit4']=np.where(test['Unit']=='Logistics',1,0)    
df_test['Unit5']=np.where(test['Unit']=='Marketing',1,0)    
df_test['Unit6']=np.where(test['Unit']=='Operarions',1,0)    
df_test['Unit7']=np.where(test['Unit']=='Production',1,0)    
df_test['Unit8']=np.where(test['Unit']=='Purchasing',1,0)    
df_test['Unit9']=np.where(test['Unit']=='Quality',1,0)    
df_test['Unit10']=np.where(test['Unit']=='R&D',1,0)    
df_test['Unit11']=np.where(test['Unit']=='Sales',1,0)    
df_test['Unit12']=np.where(test['Unit']=='Security',1,0)  



# df_test['VAR6']=test['VAR6']
# df_test['VAR5']=test['VAR5']
# df_test['VAR4']=test['VAR4']
# df_test['VAR1']=test['VAR1']
# df_test['Travel_Rate']=test['Travel_Rate']


df_test['Time_of_service']=test['Time_of_service']
df_test['Age']=test['Age']
df_test['Education']=test['Education_Level']
df_test['Relationship_Status']=np.where(test['Relationship_Status']=='Single',1,0)
df_test['Time_since_promotion']=test['Time_since_promotion']
df_test['growth_rate']=test['growth_rate']
df_test['Pay_Scale']=test['Pay_Scale']
df_test['Post_Level']=test['Post_Level']
df_test['Work_Life_balance']=test['Work_Life_balance']

In [31]:
ans=pd.DataFrame()
ans['Employee_ID']=test['Employee_ID']

In [32]:
ans['Attrition_rate'] = reg.predict(df_test)

In [33]:
ans

Employee_ID  Attrition_rate
0      EID_22713        0.187566
1       EID_9658        0.187566
2      EID_22203        0.187566
3       EID_7652        0.187566
4       EID_6516        0.187566
...          ...             ...
2995   EID_22547        0.187566
2996   EID_10066        0.187566
2997    EID_7126        0.187566
2998    EID_4929        0.187566
2999   EID_24750        0.187566

[3000 rows x 2 columns]

In [34]:
ans.to_excel(r'C:\Users\chashah4\Desktop\Output1.xlsx', index = False)